CREATE TABLE TshirtsInventory(
	ProductID INT IDENTITY(1,1) PRIMARY KEY,
	ProductName VARCHAR(50) NOT NULL,
	StyleType VARCHAR(30) NOT NULL,
	Size VARCHAR(10) NOT NULL,
	Color VARCHAR(20) NOT NULL,
	Price DECIMAL(10, 2) NOT NULL,
	Stock INT NOT NULL
);